// Generates <site>/sw.js from scripts/sw.template.js: precache list of every file
// in the site tree plus a version hash, so any content or code change produces a
// new service worker and a coherent full re-precache on clients.
//
// Usage: node scripts/build-sw.mjs [--site dir]   (defaults to site/)
import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const siteFlag = process.argv.indexOf('--site');
const SITE = siteFlag === -1 ? join(ROOT, 'site') : resolve(process.cwd(), process.argv[siteFlag + 1] ?? '');

if (!existsSync(join(SITE, 'data', 'content.json'))) {
  console.error(`${join(SITE, 'data', 'content.json')} is missing — run \`node scripts/build.mjs\` first.`);
  process.exit(1);
}

async function walk(dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await walk(full)));
    else out.push(full);
  }
  return out;
}

const files = (await walk(SITE))
  .map((f) => relative(SITE, f))
  .filter((f) => f !== 'sw.js' && !f.endsWith('.DS_Store'))
  .sort();

const hash = createHash('sha256');
for (const f of files) {
  hash.update(f);
  hash.update('\0');
  hash.update(await readFile(join(SITE, f)));
}
const version = hash.digest('hex').slice(0, 12);

const urls = files.map((f) => './' + f.split(sep).join('/'));
const template = await readFile(join(ROOT, 'scripts', 'sw.template.js'), 'utf8');
// Function replacements: as a string, `$&` and friends inside a filename would
// be expanded by String.replace, and a precache entry for a file that doesn't
// exist makes cache.addAll reject — the worker never activates and offline
// stops working site-wide while the online site looks fine.
// The banner is prepended here rather than carried in the template, so that it
// labels the file it is true of. In the template it read as a do-not-edit
// marker on the template itself.
const BANNER = '/* Generated by scripts/build-sw.mjs from scripts/sw.template.js — do not edit this file. */\n';
const sw = BANNER + template
  .replace('__VERSION__', () => version)
  .replace('__PRECACHE__', () => JSON.stringify(urls, null, 2));

await writeFile(join(SITE, 'sw.js'), sw);
console.log(`sw.js generated: version ${version}, ${urls.length} precached files`);
