// One-off: composes the two source SVGs in site/icons/ from the brand artwork,
// then rasterizes them to the PNG set the manifest needs, plus the
// apple-touch-startup-image splash set index.html links to. Uses Playwright's
// chromium (already a dev dependency) instead of adding an image toolchain.
// Run: node tools/make-icons.mjs
//
// Two different marks, because they're seen at wildly different sizes:
//   icon.svg     the full stacked "primary" lockup — app icon and splash, seen
//                at 180px+ where the wordmark is legible.
//   favicon.svg  just the stylized MIDWAY "M" — the browser tab, seen at 16px,
//                where the full lockup is an unreadable smudge.
import { chromium } from '@playwright/test';
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const ICONS = join(ROOT, 'site', 'icons');
const BRAND = join(ROOT, 'MMAF Brand Assets', 'MMAF_Primary_CMYK.svg');
const BG = '#fdf8ee';

const brandSvg = await readFile(BRAND, 'utf8');
const brandInner = brandSvg.replace(/^[\s\S]*?<svg\b[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim();
const BRAND_VB = { w: 563.8, h: 404.04 }; // viewBox of MMAF_Primary_CMYK.svg

// --- icon.svg: whole lockup, centered on the festival cream, ~84% of the box
{
  const size = 512;
  const scale = (size * 0.84) / BRAND_VB.w;
  const tx = (size - BRAND_VB.w * scale) / 2;
  const ty = (size - BRAND_VB.h * scale) / 2;
  await writeFile(
    join(ICONS, 'icon.svg'),
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size} ${size}" width="${size}" height="${size}">
  <!-- GENERATED by tools/make-icons.mjs from MMAF Brand Assets/MMAF_Primary_CMYK.svg -->
  <rect width="${size}" height="${size}" rx="96" fill="${BG}"/>
  <g transform="translate(${tx.toFixed(2)} ${ty.toFixed(2)}) scale(${scale.toFixed(5)})">
${brandInner}
  </g>
</svg>
`
  );
  console.log('icon.svg (full lockup)');
}

// --- favicon.svg: the "M" alone. The two paths below are the MIDWAY M's
// halves, lifted verbatim from the brand file; its bbox there is
// x 16.42..123.47, y 195.49..337.20.
{
  const M_PATHS = [
    'M109.02,233.77v65.15l-29.16-32.57,29.16-32.57M123.47,195.49l-63.44,70.85,63.44,70.85v-141.71h0Z',
    'M30.87,233.77l29.16,32.57-29.16,32.57v-65.15M16.42,195.49v141.71l63.44-70.85-63.44-70.85h0Z',
  ];
  const box = { x: 16.42, y: 195.49, w: 107.05, h: 141.71 };
  const size = 64;
  const scale = (size * 0.7) / box.h;
  const tx = (size - box.w * scale) / 2 - box.x * scale;
  const ty = (size - box.h * scale) / 2 - box.y * scale;
  await writeFile(
    join(ICONS, 'favicon.svg'),
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size} ${size}" width="${size}" height="${size}">
  <!-- GENERATED by tools/make-icons.mjs from MMAF Brand Assets/MMAF_Primary_CMYK.svg -->
  <rect width="${size}" height="${size}" rx="12" fill="${BG}"/>
  <g transform="translate(${tx.toFixed(2)} ${ty.toFixed(2)}) scale(${scale.toFixed(5)})" fill="#10577b">
    ${M_PATHS.map((d) => `<path d="${d}"/>`).join('\n    ')}
  </g>
</svg>
`
  );
  console.log('favicon.svg (M only)');
}

const svg = await readFile(join(ICONS, 'icon.svg'), 'utf8');
const faviconSvg = await readFile(join(ICONS, 'favicon.svg'), 'utf8');

// maskable: full-bleed square background, artwork scaled into the ~80% safe zone
const targets = [
  { file: 'icon-192.png', size: 192, scale: 1, bleed: false },
  { file: 'icon-512.png', size: 512, scale: 1, bleed: false },
  { file: 'maskable-512.png', size: 512, scale: 0.8, bleed: true },
  { file: 'apple-touch-icon.png', size: 180, scale: 1, bleed: true },
];

// apple-touch-startup-image set: festival background with the centered
// emblem, current-generation iPhone portrait sizes only (the manifest is
// portrait-locked). iOS matches a splash image by exact physical device
// pixels (CSS device-width/height * -webkit-device-pixel-ratio), so these
// three cover the current 6.1"/6.7"/6.9" iPhone size classes; other devices
// just skip the (harmless) apple-touch-startup-image lookup. Figures are the
// devices' CSS-pixel viewport, verified 2026-08 against device-spec
// references (iPhone 16: 393x852, 16 Plus: 430x932, 16 Pro Max: 440x956; all
// @3x).
const SPLASH_BG = '#fdf8ee';
const EMBLEM_FRACTION = 0.36; // emblem width as a fraction of the shorter screen dimension
const splashTargets = [
  { file: 'splash-1179x2556.png', width: 1179, height: 2556 }, // iPhone 16 / 16 Pro (393x852 @3x)
  { file: 'splash-1290x2796.png', width: 1290, height: 2796 }, // iPhone 16 Plus (430x932 @3x)
  { file: 'splash-1320x2868.png', width: 1320, height: 2868 }, // iPhone 16 Pro Max (440x956 @3x)
];

const browser = await chromium.launch();
const page = await browser.newPage();
for (const t of targets) {
  const inner = Math.round(t.size * t.scale);
  const pad = Math.round((t.size - inner) / 2);
  await page.setViewportSize({ width: t.size, height: t.size });
  await page.setContent(`<!doctype html><style>
    * { margin: 0 }
    body { width:${t.size}px; height:${t.size}px; background:${t.bleed ? '#fdf8ee' : 'transparent'} }
    img { width:${inner}px; height:${inner}px; margin:${pad}px; display:block }
  </style><img src="data:image/svg+xml;base64,${Buffer.from(svg).toString('base64')}">`);
  await page.screenshot({
    path: join(ICONS, t.file),
    omitBackground: !t.bleed,
    clip: { x: 0, y: 0, width: t.size, height: t.size },
  });
  console.log(`${t.file} (${t.size}x${t.size})`);
}
// PNG favicons. Safari renders the SVG favicon as a generic placeholder (a
// gray cube) where Chrome shows it fine, so the PNGs aren't only a legacy
// fallback — they're what Safari actually uses (QA, 2026-08-08).
for (const size of [16, 32, 48]) {
  await page.setViewportSize({ width: size, height: size });
  await page.setContent(`<!doctype html><style>
    * { margin: 0 }
    body { width:${size}px; height:${size}px }
    img { width:${size}px; height:${size}px; display:block }
  </style><img src="data:image/svg+xml;base64,${Buffer.from(faviconSvg).toString('base64')}">`);
  await page.screenshot({
    path: join(ICONS, `favicon-${size}.png`),
    clip: { x: 0, y: 0, width: size, height: size },
  });
  console.log(`favicon-${size}.png`);
}
for (const t of splashTargets) {
  const inner = Math.round(Math.min(t.width, t.height) * EMBLEM_FRACTION);
  await page.setViewportSize({ width: t.width, height: t.height });
  await page.setContent(`<!doctype html><style>
    * { margin: 0 }
    body { width:${t.width}px; height:${t.height}px; background:${SPLASH_BG};
      display:flex; align-items:center; justify-content:center }
    img { width:${inner}px; height:${inner}px; display:block }
  </style><img src="data:image/svg+xml;base64,${Buffer.from(svg).toString('base64')}">`);
  await page.screenshot({
    path: join(ICONS, t.file),
    clip: { x: 0, y: 0, width: t.width, height: t.height },
  });
  console.log(`${t.file} (${t.width}x${t.height})`);
}
await browser.close();
